name: Manual Run Example

on:
  workflow_dispatch:
    inputs:
      RUN_ENVIRONMENT:
        description: "Choose the environment to run the workflow"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - sit
          - prod

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print selected environment
        run: echo "Running in ${{ github.event.inputs.RUN_ENVIRONMENT }} environment"
